# This is a config for E2B sandbox template.
# You can use template ID (jgc5ugfq3kov7efjymik) or template name (molecule-nextjs-testTemp2) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("molecule-nextjs-testTemp2") # Sync sandbox
# sandbox = await AsyncSandbox.create("molecule-nextjs-testTemp2") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('molecule-nextjs-testTemp2')

team_id = "44f5724b-48a3-4c75-862b-6e4925e8a217"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "molecule-nextjs-testTemp2"
template_id = "jgc5ugfq3kov7efjymik"
